---
- name: Configure firewalld
  block:
    - name: Enable ports for firewalld
      firewalld:
        port: "{{ item }}"
        permanent: yes
        state: enabled
        immediate: yes
      become: yes
      with_items:
        - 80/tcp
        - 5000/tcp
        - 53/tcp
        - 53/udp
        - 6443/tcp
        - 22623/tcp

