---
- name: Get list of all VMs
  virt:
    command: list_vms
  register: all_vms
  become: yes

- name: Get list of all running VMs
  virt:
    command: list_vms
    state: running
  register: running_vms
  become: yes

- name: Destroy old router VMs, if any
  virt:
    name: "{{ item }}"
    command: destroy
  with_items: "{{ running_vms.list_vms }}"
  when: item | regex_search("router-{{ cluster }}")
  become: yes

- name: Undefine old router VMs, if any
  virt:
    name: "{{ item }}"
    command: undefine
  with_items: "{{ all_vms.list_vms }}"
  when: item | regex_search("router-{{ cluster }}")
  become: yes

- name: Find old bootstrap VM Storage
  find:
    paths: "{{ default_libvirt_pool_dir }}"
    patterns: '*-router-{{ cluster }},*-router-{{ cluster }}.ign'
  register: find_results
  become: yes

- name: Delete old router VMs Storage
  file:
    path: "{{ item['path'] }}"
    state: absent
  loop: "{{ find_results['files'] }}"
  become: yes
